spring.application.name=ecommerce
server.port = 8080

spring.data.redis.host=${REDIS_HOST:e-commerece-vbngak.serverless.euw1.cache.amazonaws.com}
spring.data.redis.port=${REDIS_PORT:6379}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
