spring.application.name=ecommerce
server.port = 8080

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

security.jwt.secret=${JWT_SECRET:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

app.security.user.username=${APP_SECURITY_USERNAME:admin}
app.security.user.password=${APP_SECURITY_PASSWORD:admin}

